name: Deploy to Render

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때마다 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. SLACK_BOT_TOKEN 환경 변수 설정
      - name: Set up SLACK_BOT_TOKEN
        run: echo "SLACK_BOT_TOKEN=${{ secrets.SLACK_BOT_TOKEN }}" >> $GITHUB_ENV

      # 5. 배포 실행
      - name: Deploy to Render
        run: |
          # Render 배포 명령어 실행
          python app.py
